version: '3.7'

services:

  server:
    build:
      context: .
      dockerfile: ./docker/dev/server/Dockerfile
    volumes:
      - ./:/app_server
    ports:
      - 8000:8000
    # env_file:
    #   - ./env/dev/.env