version: '3.7'

services:

  server:
    build:
      context: .
      dockerfile: ./docker/dev/server/Dockerfile
    command: python manage.py test api
    volumes:
      - ./app_server/:/app_server
    ports:
      - 8000:8000
    env_file:
      - ./env/dev/.env