version: '3.7'
volumes: 
  static_files:

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 80:80

  server:
    build:
      context: .
      dockerfile: ./docker/prod/server/Dockerfile
    #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn -w 4 app_server.wsgi -b 0.0.0.0:8000
    volumes:
      - static_files:/static_files
      - ./app_server/:/app_server
    ports:
      - 8000:8000
    env_file:
      - ./env/prod/.env
  